rules:
  - pattern: "^(\\w+ \\d+ \\d+:\\d+:\\d+) \\S+ \\S+\\[\\d+\\]: FAILED LOGIN \\d+ FROM (\\S+) FOR (\\w+), Authentication failure"
    severity: "[HIGH] Authentication failure"
    fields:
      - datetime
      - from
      - user
